apiVersion: apps/v1
kind: Deployment
metadata:
  name: anyzearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anyzearch
  template:
    metadata:
      labels:
        app: anyzearch
    spec:
      containers:
      - name: anyzearch
        image: ktchanhk/anyzearch:0.0.1
        ports:
        - containerPort: 3001
          hostPort: 80
        env:
        - name: STORAGE_DIR
          value: "/app/server/storage"
        - name: NODE_EXTRA_CA_CERTS
          value: "/etc/ssl/certs/ca-certificates.crt"
        - name: NODE_OPTIONS
          value: "--use-openssl-ca"
        - name: CURL_CA_BUNDLE
          value: "/etc/ssl/certs/ca-certificates.crt"
        - name: REQUESTS_CA_BUNDLE
          value: "/etc/ssl/certs/ca-certificates.crt"
        - name: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
          value: "false"
        - name: CHROME_PATH
          value: "/usr/bin/google-chrome-stable"
        - name: PUPPETEER_EXECUTABLE_PATH
          value: "/usr/bin/google-chrome-stable"
        volumeMounts:
        - name: data-storage
          mountPath: /app/server/storage
        - name: sources-list
          mountPath: /etc/apt/sources.list
        - name: env-server
          mountPath: /app/server/.env
        - name: env-frontend
          mountPath: /app/frontend/.env
        - name: docker-entrypoint
          mountPath: /usr/local/bin/docker-entrypoint.sh
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
      volumes:
      - name: data-storage
        hostPath:
          path: /home/demo/data
          type: Directory
      - name: sources-list
        hostPath:
          path: /home/demo/sources.list
          type: File
      - name: env-server
        hostPath:
          path: /home/demo/.env
          type: File
      - name: env-frontend
        hostPath:
          path: /home/demo/.env-fe
          type: File
      - name: docker-entrypoint
        hostPath:
          path: /home/demo/docker-entrypoint.sh
          type: File

---

apiVersion: v1
kind: Service
metadata:
  name: anyzearch-service
spec:
  selector:
    app: anyzearch
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: LoadBalancer
