apiVersion: apps/v1
kind: Deployment
metadata:
  name: anyzearch-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anyzearch
  template:
    metadata:
      labels:
        app: anyzearch
    spec:
      containers:
      - name: anyzearch
        image: ktchanhk/anyzearch:0.0.1
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: storage-volume
          mountPath: /app/server/storage
        - name: sources-list
          mountPath: /etc/apt/sources.list
          subPath: sources.list
        - name: env-server
          mountPath: /app/server/.env
          subPath: .env
        - name: env-frontend
          mountPath: /app/frontend/.env
          subPath: .env-fe
        - name: entrypoint-script
          mountPath: /usr/local/bin/docker-entrypoint.sh
          subPath: docker-entrypoint.sh
        env:
        - name: STORAGE_DIR
          value: "/app/server/storage"
        - name: NODE_EXTRA_CA_CERTS
          value: "/etc/ssl/certs/ca-certificates.crt"
        - name: NODE_OPTIONS
          value: "--use-openssl-ca"
        - name: CURL_CA_BUNDLE
          value: "/etc/ssl/certs/ca-certificates.crt"
        - name: REQUESTS_CA_BUNDLE
          value: "/etc/ssl/certs/ca-certificates.crt"
        - name: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
          value: "false"
        - name: CHROME_PATH
          value: "/usr/bin/google-chrome-stable"
        - name: PUPPETEER_EXECUTABLE_PATH
          value: "/usr/bin/google-chrome-stable"
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
      volumes:
      - name: storage-volume
        hostPath:
          path: ${STORAGE_LOCATION}
      - name: sources-list
        hostPath:
          path: $HOME/anyzearch/run
      - name: env-server
        hostPath:
          path: $HOME/anyzearch/run
      - name: env-frontend
        hostPath:
          path: $HOME/anyzearch/run
      - name: entrypoint-script
        hostPath:
          path: $HOME/anyzearch/run

---

apiVersion: v1
kind: Service
metadata:
  name: anyzearch-service
spec:
  selector:
    app: anyzearch
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: LoadBalancer
